import type { NextPage } from "next";
import Head from "next/head";
import { useLayoutEffect, useState } from "react";
import PaymentCard from "../components/PaymentCard/PaymentCard";
import Loading from "../components/UI/Loading";
import { getPayements } from "../utils/supabase";

const Home: NextPage = () => {
	const [loading, setLoading] = useState(true);
	const [paymentDetails, setPaymentDetails] = useState<Payment[]>();

	// useLayoutEffect(() => {
	// 	getPayements().then((data) => {
	// 		setPaymentDetails(data);
	// 		setLoading(false);
	// 	});
	// }, []);

	return (
		<>
			<Head>
				<title>Payit</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="max-w-3xl w-full mx-auto flex flex-wrap gap-8 justify-evenly sm:justify-between">
				{/* {loading || !paymentDetails ? (
					<Loading />
				) : (
					paymentDetails.map((details) => (
						<PaymentCard key={details.id} paymentDetails={details} />
					))
				)} */}
				<Loading />
				<Loading />
				<Loading />
				<PaymentCard
					paymentDetails={{
						amount: "1000",
						createdAt: new Date(),
						payee: "Tanishq Enterprises",
						id: "1",
						status: "TBD",
					}}
				/>
			</main>
		</>
	);
};

export default Home;
