import type { NextPage } from "next";
import Head from "next/head";
import PaymentCard from "../components/PaymentCard/PaymentCard";
import { getPayements } from "../utils/supabase";

const paymentDetails = {
	amount: '1000',
	recipentName: 'DLSD',
	createdAt: new Date() 
}

getPayements().then(data => console.log(data))

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Payit</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="container container-md mx-auto flex flex-wrap px-1 justify-between gap-4">
				<PaymentCard paymentDetails={paymentDetails}/>
				<PaymentCard paymentDetails={paymentDetails}/>
				<PaymentCard paymentDetails={paymentDetails}/>
				<PaymentCard paymentDetails={paymentDetails}/>
				<PaymentCard paymentDetails={paymentDetails}/>
				<PaymentCard paymentDetails={paymentDetails}/>
			</main>
		</>
	);
};

export default Home;
